version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Adjust this path if needed
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose on port 80
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: ./backend  # Adjust this path if needed
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
    environment:
      - PORT=production
      - MONGODB_URI=mongodb+srv://raphsant20:bCU4Oz6z7qJP0oBZ@cluster0.up35ing.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

networks:
  app-network:
    driver: bridge